# Use the latest Node runtime: v8.1.3 as of the time of writing
FROM node:8.1-slim

# Set the working directory to /app
WORKDIR /app

# Copy files to the working directory
ADD app.js package.json README.md /app/
ADD views /app/views

# Install any requirements
RUN npm update && npm install

# Make port 8080 available outside the container
EXPOSE 8080

# Run app.js when the container launches
CMD ["npm", "start"]
